apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
data:
  config.js: |-
    // runtime-config.js vars
      window["_env_"] =  {
        "VITE_API_URL": "{{ .Values.app.api }}",
        "VITE_ENV": "{{ .Values.app.env }}",
        "VITE_VERSION": "{{ .Values.app.version }}",
        "VITE_APP_TITLE": "{{ .Values.app.title }}",
        "VITE_OBJECT_STORAGE_URL": "{{ .Values.app.objectStorageUrl }}",
        "VITE_APP_URL": "{{ .Values.app.url }}",
        "VITE_OIDC_AUTHORITY": "{{ .Values.app.oidcAuthority }}",
        "VITE_CLIENT_ID": "{{ .Values.app.clientId }}",
        "VITE_CONDITIONS_LIBRARY_URL": "{{ .Values.app.conditionsLibraryUrl }}",
      }