"""empty message

Revision ID: 0eabfcf062e3
Revises: b573a1a7347f
Create Date: 2024-08-22 12:20:35.863982

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '0eabfcf062e3'
down_revision = 'b573a1a7347f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    package_types = sa.Table(
        'package_types',
        sa.MetaData(),
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String),
        sa.Column('created_date', sa.DateTime, default=datetime.utcnow),
    )
    item_types = sa.Table(
        'item_types',
        sa.MetaData(),
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String),
        sa.Column('created_date', sa.DateTime, default=datetime.utcnow),
    )
    package_item_types = sa.Table(
        'package_item_types',
        sa.MetaData(),
        sa.Column('package_type_id', sa.Integer),
        sa.Column('item_type_id', sa.Integer),
        sa.Column('created_date', sa.DateTime, default=datetime.utcnow),
    )
    op.bulk_insert(package_types, [
        {'name': 'Management Plan', 'created_date': datetime.utcnow()},
    ])
    op.bulk_insert(item_types, [
        {'name': 'Item 1', 'created_date': datetime.utcnow()},
        {'name': 'Item 2', 'created_date': datetime.utcnow()},
        {'name': 'Item 3', 'created_date': datetime.utcnow()},
    ])
    op.bulk_insert(package_item_types, [
        {'package_type_id': 1, 'item_type_id': 1, 'created_date': datetime.utcnow()},
        {'package_type_id': 1, 'item_type_id': 2, 'created_date': datetime.utcnow()},
        {'package_type_id': 1, 'item_type_id': 3, 'created_date': datetime.utcnow()},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM package_item_types')
    op.execute('DELETE FROM item_types')
    op.execute('DELETE FROM package_types')
    # ### end Alembic commands ###
