"""empty message

Revision ID: 20ebb6cab34d
Revises: 4a432db06bf1
Create Date: 2024-10-04 10:57:27.545797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ebb6cab34d'
down_revision = '4a432db06bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('package_item_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('package_item_types', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
