"""empty message

Revision ID: 3eb2f30b742e
Revises: 6b6adc6ea759
Create Date: 2024-09-20 08:58:43.292848

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '3eb2f30b742e'
down_revision = '6b6adc6ea759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('submission_item_type_version')
        batch_op.create_index('idx_submissions_type_item_id', ['type', 'item_id'], unique=False)
        batch_op.drop_column('version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_index('idx_submissions_type_item_id')
        batch_op.create_index('submission_item_type_version', ['item_id', 'type', 'version'], unique=True)

    # ### end Alembic commands ###
