"""Add EA certificate column

Revision ID: 41e672288201
Revises: 646de6f8c38b
Create Date: 2024-08-23 16:01:10.236907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e672288201'
down_revision = '646de6f8c38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ea_certificate', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('ea_certificate')

    # ### end Alembic commands ###
