""" Add package_metadata table

Revision ID: 427d0248f8e0
Revises: 41e672288201
Create Date: 2024-09-03 16:49:32.978514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427d0248f8e0'
down_revision = '41e672288201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('package_meta', sa.JSON(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_types', schema=None) as batch_op:
        batch_op.create_index('idx_package_types_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_types', schema=None) as batch_op:
        batch_op.drop_index('idx_package_types_name')

    op.drop_table('package_metadata')
    # ### end Alembic commands ###
