"""

Revision ID: 4a432db06bf1
Revises: 3eb2f30b742e
Create Date: 2024-10-01 15:05:18.694759

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a432db06bf1"
down_revision = "3eb2f30b742e"
branch_labels = None
depends_on = None

contact_information = "Contact Information"
contact_information_form = "Contact Information Form"
consultation_records = "Consultation Record(s)"
management_plan_submission = "Management Plan Submission"
management_plan = "Management Plan"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item_types", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sort_order", sa.Integer(), nullable=True))

    # Update item type names and set sort order
    op.execute(
        f"UPDATE item_types SET name = '{
            contact_information_form}', sort_order = 0 WHERE name = '{contact_information}'"
    )
    op.execute(
        f"UPDATE item_types SET sort_order = 1 WHERE name = '{
            consultation_records}'"
    )
    op.execute(
        f"UPDATE item_types SET name = '{
            management_plan}', sort_order = 2 WHERE name = '{management_plan_submission}'"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item_types", schema=None) as batch_op:
        batch_op.drop_column("sort_order")

    # Revert the item type names to their original values
    op.execute(
        f"UPDATE item_types SET name = '{
            contact_information}' WHERE name = '{contact_information_form}'"
    )
    op.execute(
        f"UPDATE item_types SET sort_order = NULL WHERE name = '{
            consultation_records}'"
    )
    op.execute(
        f"UPDATE item_types SET name = '{
            management_plan_submission}' WHERE name = '{management_plan}'"
    )

    # ### end Alembic commands ###
