"""Add name to account projects

Revision ID: 5a6eda61c0c4
Revises: aeb2ae9d64b9
Create Date: 2024-08-15 11:55:47.490418

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '5a6eda61c0c4'
down_revision = 'aeb2ae9d64b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_projects', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
