""" Add submitted_documents, submitted_forms and submissions tables

Revision ID: 6b6adc6ea759
Revises: 6c30d5148588
Create Date: 2024-09-10 11:11:19.917656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6adc6ea759'
down_revision = '6c30d5148588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitted_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submitted_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_json', sa.JSON(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submitted_form_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FORM', 'DOCUMENT', 'BUSINESS_DATA', name='submissiontypestatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('submitted_document_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['submitted_document_id'], ['submitted_documents.id'], ),
    sa.ForeignKeyConstraint(['submitted_form_id'], ['submitted_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('submission_item_type_version', ['item_id', 'type', 'version'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('submission_item_type_version')

    op.drop_table('submissions')
    op.drop_table('submitted_forms')
    op.drop_table('submitted_documents')
    # ### end Alembic commands ###
