""" Update item type name from 'Management Plan Form' to 'Contact information'

Revision ID: 6c30d5148588
Revises: 427d0248f8e0
Create Date: 2024-09-06 13:10:50.147040

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '6c30d5148588'
down_revision = '427d0248f8e0'
branch_labels = None
depends_on = None

management_plan_form = 'Management Plan Form'
contact_information = 'Contact Information'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # update row in item types where name = 'Management Plan Form' to have name = 'Contact information'
    op.execute(f"UPDATE item_types SET name = '{contact_information}' WHERE name = '{management_plan_form}'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
