"""Add unique constraint to account proponent_id

Revision ID: 8e112bda0a34
Revises: 97de805275ec
Create Date: 2024-07-30 13:52:28.545333

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '8e112bda0a34'
down_revision = '97de805275ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('proponent_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint('unique_account_proponent_id', ['proponent_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('unique_account_proponent_id', type_='unique')
        batch_op.alter_column('proponent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
