""" Add submission tables

Revision ID: 956afff9638f
Revises: 6c30d5148588
Create Date: 2024-09-09 15:56:42.876075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956afff9638f'
down_revision = '6c30d5148588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submitted_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submitted_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_json', sa.JSON(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submitted_form_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FORM', 'DOCUMENT', 'BUSINESS_DATA', name='submissiontypestatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('submitted_document_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['submitted_document_id'], ['submitted_documents.id'], ),
    sa.ForeignKeyConstraint(['submitted_form_id'], ['submitted_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('idx_submission_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_submission_type', ['type'], unique=False)
        batch_op.create_index('idx_submission_version', ['version'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('idx_submission_version')
        batch_op.drop_index('idx_submission_type')
        batch_op.drop_index('idx_submission_item_id')

    op.drop_table('submissions')
    op.drop_table('submitted_forms')
    op.drop_table('submitted_documents')
    # ### end Alembic commands ###
