""" Add submission method column to item_types

Revision ID: 9655618a231b
Revises: 4a432db06bf1
Create Date: 2024-10-04 15:40:00.135444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9655618a231b'
down_revision = '4a432db06bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    submission_method_enum = sa.Enum('FORM_SUBMISSION', 'DOCUMENT_UPLOAD', name='submissionmethod')
    submission_method_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_method', submission_method_enum, nullable=True))

    # Update existing records with specified names
    contact_info_form_name = 'Contact Information Form'
    management_plan_name = 'Management Plan'
    consultation_records_name = "Consultation Record(s)"

    op.execute(f"UPDATE item_types SET submission_method = 'DOCUMENT_UPLOAD' WHERE name IN ('{consultation_records_name}', '{management_plan_name}')")
    op.execute(f"UPDATE item_types SET submission_method = 'FORM_SUBMISSION' WHERE name = '{contact_info_form_name}'")

    # Make the column non-nullable
    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.alter_column('submission_method', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.drop_column('submission_method')

    submission_method_enum = sa.Enum('FORM_SUBMISSION', 'DOCUMENT_UPLOAD', name='submissionmethod')
    submission_method_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
