"""Add projects table

Revision ID: a4785881834c
Revises: 5a6eda61c0c4
Create Date: 2024-08-19 17:45:56.220026

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a4785881834c'
down_revision = '5a6eda61c0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('proponent_id', sa.String(), nullable=False),
    sa.Column('proponent_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proponent_id')
    )
    with op.batch_alter_table('account_projects', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('projects')
    # ### end Alembic commands ###
