""" Add folder column to submitted_documents

Revision ID: acc74a5b1219
Revises: d8ac6fff4ec6
Create Date: 2024-10-02 14:36:29.181411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc74a5b1219'
down_revision = 'd8ac6fff4ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submitted_documents', schema=None) as batch_op:
        batch_op.drop_column('folder')

    # ### end Alembic commands ###
