""" Add version column to submissions

Revision ID: d8ac6fff4ec6
Revises: 3eb2f30b742e
Create Date: 2024-09-24 10:17:56.906370

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'd8ac6fff4ec6'
down_revision = '3eb2f30b742e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
