/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OidcCallbackImport } from './routes/oidc-callback'
import { Route as ErrorImport } from './routes/error'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as EaoPlansIndexImport } from './routes/eao-plans/index'
import { Route as EaoPlansPlanIdImport } from './routes/eao-plans/$planId'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminLoginImport } from './routes/_authenticated/admin-login'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedProjectsIndexImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedRegistrationCreateAccountImport } from './routes/_authenticated/registration/create-account'
import { Route as AuthenticatedRegistrationAddProjectsImport } from './routes/_authenticated/registration/add-projects'
import { Route as AuthenticatedRegistrationAccountAccountIdProjectsImport } from './routes/_authenticated/registration/account/$accountId/projects'

// Create Virtual Routes

const NewpageLazyImport = createFileRoute('/newpage')()
const AboutpageLazyImport = createFileRoute('/aboutpage')()

// Create/Update Routes

const NewpageLazyRoute = NewpageLazyImport.update({
  path: '/newpage',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/newpage.lazy').then((d) => d.Route))

const AboutpageLazyRoute = AboutpageLazyImport.update({
  path: '/aboutpage',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/aboutpage.lazy').then((d) => d.Route))

const OidcCallbackRoute = OidcCallbackImport.update({
  path: '/oidc-callback',
  getParentRoute: () => rootRoute,
} as any)

const ErrorRoute = ErrorImport.update({
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EaoPlansIndexRoute = EaoPlansIndexImport.update({
  path: '/eao-plans/',
  getParentRoute: () => rootRoute,
} as any)

const EaoPlansPlanIdRoute = EaoPlansPlanIdImport.update({
  path: '/eao-plans/$planId',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAdminLoginRoute = AuthenticatedAdminLoginImport.update({
  path: '/admin-login',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProjectsIndexRoute = AuthenticatedProjectsIndexImport.update(
  {
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedRegistrationCreateAccountRoute =
  AuthenticatedRegistrationCreateAccountImport.update({
    path: '/registration/create-account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedRegistrationAddProjectsRoute =
  AuthenticatedRegistrationAddProjectsImport.update({
    path: '/registration/add-projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedRegistrationAccountAccountIdProjectsRoute =
  AuthenticatedRegistrationAccountAccountIdProjectsImport.update({
    path: '/registration/account/$accountId/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/oidc-callback': {
      id: '/oidc-callback'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackImport
      parentRoute: typeof rootRoute
    }
    '/aboutpage': {
      id: '/aboutpage'
      path: '/aboutpage'
      fullPath: '/aboutpage'
      preLoaderRoute: typeof AboutpageLazyImport
      parentRoute: typeof rootRoute
    }
    '/newpage': {
      id: '/newpage'
      path: '/newpage'
      fullPath: '/newpage'
      preLoaderRoute: typeof NewpageLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin-login': {
      id: '/_authenticated/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AuthenticatedAdminLoginImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/eao-plans/$planId': {
      id: '/eao-plans/$planId'
      path: '/eao-plans/$planId'
      fullPath: '/eao-plans/$planId'
      preLoaderRoute: typeof EaoPlansPlanIdImport
      parentRoute: typeof rootRoute
    }
    '/eao-plans/': {
      id: '/eao-plans/'
      path: '/eao-plans'
      fullPath: '/eao-plans'
      preLoaderRoute: typeof EaoPlansIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/registration/add-projects': {
      id: '/_authenticated/registration/add-projects'
      path: '/registration/add-projects'
      fullPath: '/registration/add-projects'
      preLoaderRoute: typeof AuthenticatedRegistrationAddProjectsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/registration/create-account': {
      id: '/_authenticated/registration/create-account'
      path: '/registration/create-account'
      fullPath: '/registration/create-account'
      preLoaderRoute: typeof AuthenticatedRegistrationCreateAccountImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/registration/account/$accountId/projects': {
      id: '/_authenticated/registration/account/$accountId/projects'
      path: '/registration/account/$accountId/projects'
      fullPath: '/registration/account/$accountId/projects'
      preLoaderRoute: typeof AuthenticatedRegistrationAccountAccountIdProjectsImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedAdminLoginRoute,
    AuthenticatedProfileRoute,
    AuthenticatedRegistrationAddProjectsRoute,
    AuthenticatedRegistrationCreateAccountRoute,
    AuthenticatedProjectsIndexRoute,
    AuthenticatedUsersIndexRoute,
    AuthenticatedRegistrationAccountAccountIdProjectsRoute,
  }),
  ErrorRoute,
  OidcCallbackRoute,
  AboutpageLazyRoute,
  NewpageLazyRoute,
  EaoPlansPlanIdRoute,
  EaoPlansIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/error",
        "/oidc-callback",
        "/aboutpage",
        "/newpage",
        "/eao-plans/$planId",
        "/eao-plans/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/admin-login",
        "/_authenticated/profile",
        "/_authenticated/registration/add-projects",
        "/_authenticated/registration/create-account",
        "/_authenticated/projects/",
        "/_authenticated/users/",
        "/_authenticated/registration/account/$accountId/projects"
      ]
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/oidc-callback": {
      "filePath": "oidc-callback.tsx"
    },
    "/aboutpage": {
      "filePath": "aboutpage.lazy.tsx"
    },
    "/newpage": {
      "filePath": "newpage.lazy.tsx"
    },
    "/_authenticated/admin-login": {
      "filePath": "_authenticated/admin-login.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/eao-plans/$planId": {
      "filePath": "eao-plans/$planId.tsx"
    },
    "/eao-plans/": {
      "filePath": "eao-plans/index.tsx"
    },
    "/_authenticated/registration/add-projects": {
      "filePath": "_authenticated/registration/add-projects.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/registration/create-account": {
      "filePath": "_authenticated/registration/create-account.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/": {
      "filePath": "_authenticated/projects/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/registration/account/$accountId/projects": {
      "filePath": "_authenticated/registration/account/$accountId/projects.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
