apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.app_group }}
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}
stringData:
  KEYCLOAK_ADMIN_CLIENT: {{ .Values.auth.keycloak.adminClientId }}
  KEYCLOAK_ADMIN_SECRET: {{ .Values.auth.keycloak.adminClientSecret }}
